FROM 113355358853.dkr.ecr.eu-west-1.amazonaws.com/ho/hmpo/lev/fro/cypress-testing:abeda9a0033970f2dcfecd8c4f41bed6d0363343
#FROM cypress/included:cypress-12.17.1-node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1

#ENV HTTP_PROXY='http://proxy.local:8080'
#ENV HTTPS_PROXY='http://proxy.local:8080'

USER root
#WORKDIR /app
COPY ./ ./

#ENV CYPRESS_INSTALL_BINARY=../root/.cache/Cypress/12.17.1/Cypress/Cypress

RUN npm ci -D

CMD [ "npm", "run", "test:ui" ]
