version: "3"
services:
  lev-web-ui:
    build: .
    ports:
    - "8001:8001"
    environment:
      API_HOST: mock-api
      API_PORT: 8080
      MOCK: "true"
      IAM_USER: minch.yoda@theforce.gov
      ROLES: birth,death,user-management
      API_ORIGINAL_CLIENT: "lev-web-ui"
      REDIS_CONNECTION_STRING: "redis://redis-service:6379"
#      REDIS_HOST: redis-service
#      REDIS_PORT: 6379
      FLS_ENABLED: "false"
      IS_EXTERNAL: "true"
    depends_on:
    - redis-service
    - mock-api
  mock-api:
    image: 113355358853.dkr.ecr.eu-west-1.amazonaws.com/ho/hmpo/lev/api/lev-api:4158fe8d0dee3798b80beb41c2f30b61c36d7a5f
    environment:
      MOCK: "true"
    ports:
    - "8080:8080"
  redis-service:
    image: 113355358853.dkr.ecr.eu-west-1.amazonaws.com/ho/hmpo/lev/bac/lev-redis:444d9ba50bb252b24de6b3a20ba7c6a9370a79e3
    ports:
    - "6379:6379"
