FROM 113355358853.dkr.ecr.eu-west-1.amazonaws.com/ho/hmpo/lev/fro/cypress-testing:9e1bcb6e49020d5ad571c3f43514623b46072dd5

WORKDIR /app
COPY ./ /app

RUN npm ci -D

ENV NO_COLOR=1

ENTRYPOINT ["/usr/local/bin/npm",  "run", "test:ui" ]
