FROM 113355358853.dkr.ecr.eu-west-1.amazonaws.com/ho/hmpo/lev/fro/cypress-testing:8c64f6e43a7e98ec1a25a1bf2bf7d830ef151e56

WORKDIR /app
COPY ./ /app

RUN npm ci -D

ENV NO_COLOR=1

ENTRYPOINT ["/usr/local/bin/npm",  "run", "test:ui" ]
